<?php

use Illuminate\Support\Str;
use PaulhenriL\LaravelPubSub\EventBus\AwsEventBridge;

return [
    /**
     * When the events will be sent through the event bus we will prefix them
     * with this value. It makes it easier for another application to listen on
     * events generated by a particular application.
     */
    'events_prefix' => Str::slug(env('APP_NAME', 'laravel'), '_') . ':',

    /**
     * The class of the event bus that should be used.
     */
    'event_bus' => AwsEventBridge::class,
];
